# Generated by Django 5.2.8 on 2025-11-10 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prep_time', models.IntegerField(help_text='Preparation time in minutes')),
                ('cook_time', models.IntegerField(help_text='Cooking time in minutes')),
                ('servings', models.IntegerField(help_text='Number of servings')),
                ('notes', models.TextField(blank=True, help_text='Optional notes, tips, or variations', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='goodTastesLike2.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='Ingredients', help_text="Group (e.g., 'Wet', 'Dry', 'Garnish')", max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=50)),
                ('units', models.CharField(choices=[('cup', 'cup(s)'), ('tsp', 'teaspoon(s)'), ('Tbsp', 'tablespoon(s)'), ('oz', 'ounce(s)'), ('g', 'gram(s)'), ('kg', 'kilogram(s)'), ('ml', 'milliliter(s)'), ('l', 'liter(s)'), ('qty', 'qty'), ('pinch', 'pinch'), ('to taste', 'to taste')], max_length=50)),
                ('notes', models.CharField(blank=True, help_text="Optional prep notes (e.g., 'chopped', 'melted')", max_length=255, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='goodTastesLike2.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='goodTastesLike2.recipe')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
    ]
