# Generated by Django 5.2.8 on 2025-11-11 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodTastesLike2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['group', 'order']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='tags', to='goodTastesLike2.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='group',
            field=models.CharField(choices=[('wet', 'Wet'), ('dry', 'Dry'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(choices=[('cup', 'Cup'), ('cups', 'Cups'), ('tsp', 'Teaspoon'), ('teaspoon', 'Teaspoon'), ('teaspoons', 'Teaspoons'), ('Tbs', 'Tablespoon'), ('Tbsp', 'Tablespoon'), ('tablespoon', 'Tablespoon'), ('tablespoons', 'Tablespoons'), ('oz', 'Ounce'), ('ounce', 'Ounce'), ('ounces', 'Ounces'), ('g', 'Gram'), ('gram', 'Gram'), ('grams', 'Grams'), ('kg', 'Kilogram'), ('kilogram', 'Kilogram'), ('kilograms', 'Kilograms'), ('ml', 'Milliliter'), ('milliliter', 'Milliliter'), ('milliliters', 'Milliliters'), ('l', 'Liter'), ('liter', 'Liter'), ('liters', 'Liters'), ('qty', 'Quantity'), ('pinch', 'Pinch'), ('to taste', 'To Taste')], max_length=20),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='step_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(help_text='Cooking time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(help_text='Preparation time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
